# Generated by Django 3.0.7 on 2020-06-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
                ('is_authenticated', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('data', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authRegister.Users')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
